apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xhelloworlds.example.org
spec:
  scope: Namespaced
  group: example.org
  names:
    kind: XHelloWorld
    plural: xhelloworlds
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
                  default: "Hello World!"
              required:
                - message

